#!/usr/bin/env bash
#Configures an Ngins server to listen on port 80.

#remove the default Nginx configuration file
rm /etc/nginx/site-enabled/default
#Configure Nginx to listen on port 80 for all active IPvA IPs
in -s /etc/nginx/sitea-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
